### ISSUE TITLE
Create a way to set the host programmatically at runtime

### ISSUE THREAD

**Issue by Essbante** [roots-id/wal-library#16]
**Is your feature request related to a problem? Please describe.**
on android phones is not easy to set environment variables for runtime.  

**Describe the solution you'd like**
so if you could give me a way to set the host programmatically at runtime that would help RootsWallet to be able to toggle the host (it would be in our settings screen or something)

**Comment by Essbante** [comment]
@2byrds  you can do:

`GrpcConfig.host = "im.a.host"`
`GrpcConfig.port= "5000"`

to change the values programmatically.

**Comment by 2byrds** [comment]
yatze!  i'll try it out today
