### ISSUE TITLE
Wal-lib 2.0.1 - Cannot create new Wallet

### ISSUE THREAD

**Issue by 2byrds** [roots-id/wal-library#38]
**Describe the bug**
When trying to create a wallet, RootsWallet needs to serialize JSON representing the wallet.
During JSON serialization we are getting:
CreateWalletScreen - Creating wallet failed [Error: Exception in HostFunction: kotlinx.serialization.SerializationException: Class 'WalletDocument' is not registered for polymorphic serialization in the scope of 'Wallet'.
Mark the base class as 'sealed' or register the serializer explicitly.] [native code]

**To Reproduce**
https://github.com/roots-id/rootswallet/blob/wal-lib-2x/android/app/src/main/java/com/rootswallet/PrismModule.kt#L60

**Expected behavior**
createWallet and serialize it

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rogelio-blanco** [comment]
@2byrds can you try changing 
`return Json.encodeToString<Wallet>(cliWal);`
with 
`return Json.encodeToString<WalletDocument>(cliWal);`

**Comment by 2byrds** [comment]
Worked great, thank you @rogelio-blanco !
